name: "Build Modified Visual Studio Code"
description: 'Builds Visual Studio Code from a specific release'
inputs:
  release:
    description: 'Release to build'
    required: false
  repository:
    description: 'Repository to build from'
    required: false
    default: 'microsoft/vscode'

runs:
  using: "node16"
  main: "dist/index.js"
