name: "Build Modified Visual Studio Code"
description: 'Builds Visual Studio Code from a specific release'
inputs:
  release:
    description: 'Release to build'
    required: false
  repository:
    description: 'Repository to build from'
    required: false
    default: 'microsoft/vscode'
  type:
    description: 'Type to run (not what you think it is)'
    required: false
    default: 'build'

runs:
  using: "node16"
  main: "dist/index.js"
