name: Build Modified Visual Studio Code - Windows

on:
  workflow_dispatch:
    inputs:
      release:
        description: "Release to build"
        required: true
        type: string
  workflow_run:
    workflows: ["Build Action"]
    types:
      - completed
  schedule:
    - cron: "0 */6 * * *"
  push:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-code:
    strategy:
      fail-fast: false
      matrix:
        vscode_arch:
          - x64
          - ia32
          - arm64
    env:
      VSCODE_ARCH: ${{ matrix.vscode_arch }}
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build Code
        uses: ./
        with:
          release: ${{ inputs.release }}
          repository: microsoft/vscode
