name: Build Modified Visual Studio Code

on:
  workflow_dispatch:
    inputs:
      release:
        description: "Release to build"
        required: true
        type: string

  schedule:
    - cron: "0 */6 * * *"
  push:
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-code:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: windows
          - os: macos-latest
            platform: darwin
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build Code
        uses: ./
        with:
          release: ${{ inputs.release }}
          repository: microsoft/vscode
          platform: ${{ matrix.platform }}
        
