name: Build Modified Visual Studio Code

on:
  workflow_dispatch:
    inputs:
      release:
        description: "Release to build"
        required: true
        type: string
  workflow_run:
    workflows: ["Build Action"]
    types:
      - completed
  schedule:
    - cron: "0 */6 * * *"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-code:
    env:
      VSCODE_ARCH: ${{ matrix.vscode_arch }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            vscode_arch: x64
          - os: windows-latest
            vscode_arch:
              - x64
              - ia32
              - arm64
          - os: macos-latest
            vscode_arch: x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Download Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          echo "Installing Linux dependencies"
      - name: Build Code
        uses: ./
        with:
          release: ${{ inputs.release }}
          repository: microsoft/vscode
